### ISSUE TITLE
HPE_INVALID_CONSTANT error occurred in Node.js client when receive empty string

### ISSUE THREAD

**Issue by carrotflakes** [fukamachi/woo#85]
Server:
``` lisp
(ql:quickload :clack)

(defvar *hander*
  (clack:clackup
   (lambda (env)
     (declare (ignore env))
     '(200 (:content-type "text/plain") ("")))
   :port 3000
   :server :woo))
```

Client in Node.js with [`request`](https://github.com/request/request) library:
``` js
const request = require('request');

request.get('http://localhost:3000/', (err, res, body) => console.log([err, res, body]));
```

Run this client then get following result:
```
[ { Error: Parse Error
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20) bytesParsed: 115, code: 'HPE_INVALID_CONSTANT' },
  undefined,
  undefined ]
```

Node.js version: v10.15.0

I guess woo returns invalid response. 🤔

**Comment by fukamachi** [comment]
Thank you for reporting. I don’t have time to look into this, but the error
would be shown when the response length cannot be determine. I suppose Woo
returns Transfer-Encoding: chunked even for empty responses.

2019年6月20日(木) 23:23 carrotflakes <notifications@github.com>:
